# Generated by Django 3.2.4 on 2021-06-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryRecipe',
            new_name='RecipeCategory',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='recipecategory',
            table='recipes_categories',
        ),
    ]
