# Generated by Django 3.2.4 on 2021-06-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_category_id_recipe_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipecategory',
            table='recipe_categories',
        ),
    ]
