# Generated by Django 3.2.4 on 2021-06-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('new_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='user.user')),
                ('old_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old', to='user.user')),
            ],
            options={
                'db_table': 'points',
            },
        ),
    ]
