# Generated by Django 3.2.4 on 2021-06-09 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('like', '0001_initial'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoryIngredient',
            new_name='IngredientSubCategory',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='ingredientsubcategory',
            old_name='main',
            new_name='main_category_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user_id',
            field=models.ManyToManyField(through='like.Like', to='user.User'),
        ),
        migrations.AddField(
            model_name='maincategoryingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ingredientsubcategory',
            table='ingredient_sub_categories',
        ),
    ]
