# Generated by Django 3.2.4 on 2021-06-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20210609_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategoryIngredient',
            new_name='IngredientMainCategory',
        ),
        migrations.AlterModelTable(
            name='ingredientmaincategory',
            table='ingredients_main_categories',
        ),
    ]
