# Generated by Django 3.2.4 on 2021-06-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_auto_20210609_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ingredientsubcategory',
            old_name='main_category_id',
            new_name='main_category',
        ),
    ]
