# Generated by Django 3.2.4 on 2021-06-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_auto_20210609_1152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientsubcategory',
            table='ingredients_sub_categories',
        ),
    ]
