# Generated by Django 3.2.4 on 2021-06-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_alter_ingredientsubcategory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientmaincategory',
            table='ingredient_main_categories',
        ),
        migrations.AlterModelTable(
            name='ingredientrecipe',
            table='ingredient_recipes',
        ),
        migrations.AlterModelTable(
            name='ingredientsubcategory',
            table='ingredient_sub_categories',
        ),
    ]
