# Generated by Django 3.2.4 on 2021-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('soft_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
