# Generated by Django 3.2.4 on 2021-06-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='soft_delete',
        ),
    ]
