# Generated by Django 3.2.4 on 2021-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
