# Generated by Django 3.2.4 on 2021-06-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_sofrt_delete'),
        ('cart', '0004_rename_sofrt_delete_cart_soft_delete'),
    ]

    operations = [
    ]
