# Generated by Django 3.2.4 on 2021-06-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=45, null=True, unique=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]