# Generated by Django 3.2.4 on 2021-06-09 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('ingredient', '0002_auto_20210609_0424'),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='ingredient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_ingredient', to='ingredient.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='user.user'),
            preserve_default=False,
        ),
    ]
