# Generated by Django 3.2.4 on 2021-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='false_delete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
