# Generated by Django 3.2.4 on 2021-06-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210609_0424'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderstatus',
            table='orders_statuses',
        ),
    ]
