# Generated by Django 3.2.4 on 2021-06-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(through='order.OrderItem', to='cart.Cart'),
        ),
    ]
