# Generated by Django 3.2.4 on 2021-06-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sofrt_delete',
            field=models.BooleanField(default=False),
        ),
    ]
