# Generated by Django 3.2.4 on 2021-06-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_sofrt_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sofrt_delete',
        ),
    ]
